# Generated by Django 2.1.7 on 2019-03-11 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostgroup',
            old_name='hosts_to_remote_users',
            new_name='host_to_remote_users',
        ),
    ]
