# Generated by Django 2.1.7 on 2019-03-11 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20190311_1721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remoteuser',
            old_name='auto_type',
            new_name='auth_type',
        ),
        migrations.AlterUniqueTogether(
            name='remoteuser',
            unique_together={('auth_type', 'username', 'password')},
        ),
    ]
