# Generated by Django 2.1.7 on 2019-03-11 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20190311_1742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host',
            old_name='ipaddr',
            new_name='ip_addr',
        ),
    ]
