# Generated by Django 2.1.7 on 2019-03-20 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_tasklogdetail_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('cmd', '批量命令'), ('file-transfer', '文件传输')], max_length=64),
        ),
    ]
